# Generated by Django 4.1.7 on 2023-04-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default='09038336449', max_length=12),
            preserve_default=False,
        ),
    ]
