# Generated by Django 4.1.7 on 2023-04-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_person_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='facebook',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='instagram',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='linkedin',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
